services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    restart: unless-stopped
    command: ["npm", "run", "start:prod"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: ezsalon@123
      DB_NAME: ezsalon
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:7-alpine
    container_name: ezsalon_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

volumes:
  redis_data:
    driver: local
