import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateProductsTable1761328627286 implements MigrationInterface {
    name = 'UpdateProductsTable1761328627286'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_users_created_by\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_users_role\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP FOREIGN KEY \`FK_social_accounts_customer\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP FOREIGN KEY \`FK_social_accounts_user\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP FOREIGN KEY \`FK_customer_salons_customer\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP FOREIGN KEY \`FK_customer_salons_salon\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_role_permissions_permission\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_role_permissions_role\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_created_by\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_role\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_role_name\` ON \`roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_permission_name\` ON \`permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_salon_email\` ON \`salons\``);
        await queryRunner.query(`DROP INDEX \`IDX_social_customer\` ON \`social_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_social_provider_id\` ON \`social_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_social_user\` ON \`social_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_customer_email\` ON \`customers\``);
        await queryRunner.query(`DROP INDEX \`IDX_customer_salons_customer\` ON \`customer_salons\``);
        await queryRunner.query(`DROP INDEX \`IDX_customer_salons_salon\` ON \`customer_salons\``);
        await queryRunner.query(`DROP INDEX \`IDX_role_permissions_permission\` ON \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_role_permissions_role\` ON \`role_permissions\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`provider\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`provider_id\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`email_address\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`full_name\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`user_uuid\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP COLUMN \`relationship_status\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP COLUMN \`joined_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`price\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`duration_minutes\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`category\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`is_active\``);
        await queryRunner.query(`ALTER TABLE \`salons\` ADD \`logo_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`social_uuid\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`social_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`social_email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`social_name_display\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`profile_data\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`password\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`customer_address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`customer_notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`is_owner\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`created_by_uuid\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`created_by_user_uuid\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD \`uuid\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD \`role_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`status\` enum ('ACTIVE', 'INACTIVE', 'DRAFT') NOT NULL DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`type\` enum ('SUBSCRIPTION', 'ONE_TIME') NOT NULL DEFAULT 'SUBSCRIPTION'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price_cents\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`currency\` varchar(3) NOT NULL DEFAULT 'USD'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`billing_interval\` enum ('day', 'week', 'month', 'year') NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`billing_interval_count\` int NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`stripe_product_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`stripe_price_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`max_salons\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`max_staff_per_salon\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`display_order\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`trial_period_days\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`created_by_uuid\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_d1a16364b1f276e14e8e4cfc47\` (\`email_address\`)`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD UNIQUE INDEX \`IDX_ac35f51a0f17e3e1fe12112603\` (\`role_name\`)`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD UNIQUE INDEX \`IDX_b990eff1fc3540798960d80e45\` (\`permission_name\`)`);
        await queryRunner.query(`ALTER TABLE \`salons\` ADD UNIQUE INDEX \`IDX_df28faac07f6c84466f251505d\` (\`email_address\`)`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD UNIQUE INDEX \`IDX_7c45b625d7a179409a90f485ce\` (\`email_address\`)`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD UNIQUE INDEX \`IDX_46c5f573cb24bdc6e81b8ef250\` (\`phone_number\`)`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`status\` \`status\` varchar(255) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP COLUMN \`customer_uuid\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD \`customer_uuid\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP COLUMN \`salon_uuid\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD \`salon_uuid\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_7be6db7b59fb622e6c16ba124c\` ON \`role_permissions\` (\`role_uuid\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f985b194ff27dde81fb470c192\` ON \`role_permissions\` (\`permission_uuid\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_b925bcec35ac48b9393685253d6\` FOREIGN KEY (\`role_uuid\`) REFERENCES \`roles\`(\`uuid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_6b6a33e57a4651825262ea22240\` FOREIGN KEY (\`created_by_uuid\`) REFERENCES \`users\`(\`uuid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD CONSTRAINT \`FK_9797f54f7791a6524c9b7a28ce9\` FOREIGN KEY (\`customer_uuid\`) REFERENCES \`customers\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_5aeb56ea2864883c0ea024d9e86\` FOREIGN KEY (\`created_by_uuid\`) REFERENCES \`customers\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_8b58ff8891253c43c3bcf3b886d\` FOREIGN KEY (\`created_by_user_uuid\`) REFERENCES \`users\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD CONSTRAINT \`FK_040e03d3d7fcb3ff3906d65f46d\` FOREIGN KEY (\`customer_uuid\`) REFERENCES \`customers\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD CONSTRAINT \`FK_4cedc6dcff134b602ba138f6f61\` FOREIGN KEY (\`salon_uuid\`) REFERENCES \`salons\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_bbd15d85d6768b8d45750a6e09b\` FOREIGN KEY (\`created_by_uuid\`) REFERENCES \`users\`(\`uuid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_7be6db7b59fb622e6c16ba124c8\` FOREIGN KEY (\`role_uuid\`) REFERENCES \`roles\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_f985b194ff27dde81fb470c1920\` FOREIGN KEY (\`permission_uuid\`) REFERENCES \`permissions\`(\`uuid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_f985b194ff27dde81fb470c1920\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_7be6db7b59fb622e6c16ba124c8\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_bbd15d85d6768b8d45750a6e09b\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP FOREIGN KEY \`FK_4cedc6dcff134b602ba138f6f61\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP FOREIGN KEY \`FK_040e03d3d7fcb3ff3906d65f46d\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_8b58ff8891253c43c3bcf3b886d\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_5aeb56ea2864883c0ea024d9e86\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP FOREIGN KEY \`FK_9797f54f7791a6524c9b7a28ce9\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_6b6a33e57a4651825262ea22240\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_b925bcec35ac48b9393685253d6\``);
        await queryRunner.query(`DROP INDEX \`IDX_f985b194ff27dde81fb470c192\` ON \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_7be6db7b59fb622e6c16ba124c\` ON \`role_permissions\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP COLUMN \`salon_uuid\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD \`salon_uuid\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP COLUMN \`customer_uuid\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD \`customer_uuid\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`status\` \`status\` varchar(255) NOT NULL DEFAULT 'ACTIVED'`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP INDEX \`IDX_46c5f573cb24bdc6e81b8ef250\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP INDEX \`IDX_7c45b625d7a179409a90f485ce\``);
        await queryRunner.query(`ALTER TABLE \`salons\` DROP INDEX \`IDX_df28faac07f6c84466f251505d\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP INDEX \`IDX_b990eff1fc3540798960d80e45\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP INDEX \`IDX_ac35f51a0f17e3e1fe12112603\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_d1a16364b1f276e14e8e4cfc47\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`created_by_uuid\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`trial_period_days\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`display_order\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`max_staff_per_salon\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`max_salons\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`stripe_price_id\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`stripe_product_id\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`billing_interval_count\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`billing_interval\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`currency\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`price_cents\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`type\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP COLUMN \`role_name\``);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` DROP COLUMN \`uuid\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`created_by_user_uuid\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`created_by_uuid\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`is_owner\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`customer_notes\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`customer_address\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`profile_data\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`social_name_display\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`social_email\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`social_name\``);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` DROP COLUMN \`social_uuid\``);
        await queryRunner.query(`ALTER TABLE \`salons\` DROP COLUMN \`logo_url\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`is_active\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`category\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`duration_minutes\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price\` decimal NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD \`joined_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD \`relationship_status\` varchar(255) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`user_uuid\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`full_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`email_address\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`provider_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD \`provider\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_role_permissions_role\` ON \`role_permissions\` (\`role_uuid\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_role_permissions_permission\` ON \`role_permissions\` (\`permission_uuid\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_customer_salons_salon\` ON \`customer_salons\` (\`salon_uuid\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_customer_salons_customer\` ON \`customer_salons\` (\`customer_uuid\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_customer_email\` ON \`customers\` (\`email_address\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_social_user\` ON \`social_accounts\` (\`user_uuid\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_social_provider_id\` ON \`social_accounts\` (\`provider\`, \`provider_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_social_customer\` ON \`social_accounts\` (\`customer_uuid\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_salon_email\` ON \`salons\` (\`email_address\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_permission_name\` ON \`permissions\` (\`permission_name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_role_name\` ON \`roles\` (\`role_name\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_user_role\` ON \`users\` (\`role_uuid\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_user_email\` ON \`users\` (\`email_address\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_user_created_by\` ON \`users\` (\`created_by_uuid\`)`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_role_permissions_role\` FOREIGN KEY (\`role_uuid\`) REFERENCES \`roles\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_role_permissions_permission\` FOREIGN KEY (\`permission_uuid\`) REFERENCES \`permissions\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD CONSTRAINT \`FK_customer_salons_salon\` FOREIGN KEY (\`salon_uuid\`) REFERENCES \`salons\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`customer_salons\` ADD CONSTRAINT \`FK_customer_salons_customer\` FOREIGN KEY (\`customer_uuid\`) REFERENCES \`customers\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD CONSTRAINT \`FK_social_accounts_user\` FOREIGN KEY (\`user_uuid\`) REFERENCES \`users\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`social_accounts\` ADD CONSTRAINT \`FK_social_accounts_customer\` FOREIGN KEY (\`customer_uuid\`) REFERENCES \`customers\`(\`uuid\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_users_role\` FOREIGN KEY (\`role_uuid\`) REFERENCES \`roles\`(\`uuid\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_users_created_by\` FOREIGN KEY (\`created_by_uuid\`) REFERENCES \`users\`(\`uuid\`) ON DELETE SET NULL ON UPDATE CASCADE`);
    }

}
